---
title: "Equipo1"
author: "DenniseL"
date: "29/4/2021"
output: html_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
remotes::install_github("cienciadedatos/datos")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(datos)
library(tidyverse)
Pingus<-datos::pinguinos
Adelia<-Pingus%>%filter(especie=='Adelia')
```

##GRAFICA
```{r}
Adelia_mod <- ggplot(Adelia, 
            aes(x=masa_corporal_g, y=largo_aleta_mm))+
       geom_point(alpha = 0.1)+
       geom_smooth(method="lm")+
       xlab("Masa Corporal (gr)")+
       ylab("Longitud Aleta")
Adelia_mod
```

```{r}
modelo_Adelia<- lm(data=Adelia,
                       masa_corporal_g ~ largo_aleta_mm)
modelo_Adelia
```
```{r}
summary(modelo_Adelia)
TablaAdelia <- broom::tidy(modelo_Adelia)
```
##TABLA MODELO
```{r}
#install.packages("kableExtra")
library(kableExtra)
kbl(TablaAdelia, 
    booktabs = T, caption = "Demo Table") %>% #Titulo
    kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F)
```